name: AutoTest
on: [push]
jobs:
  find_lowest_number_test:
    name: Find Lowest Number Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Test case 1.1 Produce output
      run: python find_lowest_number.py test_data/test1_input.txt test_data/test1_output.txt
    - name: Test case 1.2 Compare expected output to actual output
      run: diff test_data/test1_expected.txt test_data/test1_output.txt
      
    - name: Test case 2.1 Produce output
      run: python find_lowest_number.py test_data/test2_input.txt test_data/test2_output.txt
    - name: Test case 2.2 Compare expected output to actual output
      run: diff test_data/test2_expected.txt test_data/test2_output.txt
      
    - name: Test case 3.1 Produce output
      run: python find_lowest_number.py test_data/test3_input.txt test_data/test3_output.txt
    - name: Test case 3.2 Compare expected output to actual output
      run: diff test_data/test3_expected.txt test_data/test3_output.txt
